--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/usy4/Suggestions
build-by-default: true
branches:
- main
projects:
  Suggestions:
    path: ""
    icon: "Suggestions.png"
    libs:
    libs:
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.0.0
...
